# Generated by Django 4.0.5 on 2022-09-12 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr_management', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='repassword',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='sale_end',
        ),
    ]
